language: php
php:
  - "7.1"
  - "7.2"
  - "7.3"
before_script:
  - composer install

env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

matrix:
    include:
        - php: 7.1
          env: 'COMPOSER_FLAGS="--prefer-stable"'

script:
  - vendor/bin/phpcs --standard=psr12 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  wget https://scrutinizer-ci.com/ocular.phar
  php ocular.phar code-coverage:upload --format=php-clover coverage.clover
